### PR TITLE
fixes #68

### LINKED ISSUE #68: Checkin endpoint docs is incorrect
Docs for checkin guest endpoint states that I should send a 
 `timestamp: Date.now(),` 
which results in a weird date (2008 and a random day_month).

To send a correct date I had to udpate to
` timestamp: Math.round(+new Date() / 1000)`

Can the docs be updated accordingly or maybe there is another solution that would work better?

### PR DESCRIPTION
**Pull request by joanna-pw**

### CODE REVIEW

**Comment by mpointl** [comment]
Please review @MaxProrok1 
I´m not qualified to review code changes :-)

**Review by MaxProrok1 — APPROVED** [review]

**Comment by MaxProrok1** [comment]
@mpointl I don't have the rights to merge, maybe @orkhanahmadov can help with that

**Comment by joanna-pw** [comment]
Sorry Max, you were the suggested person to review a PR - I will add Orkhan
:)

pt., 13 gru 2024 o 14:39 MaxProrok1 ***@***.***> napisał(a):

**Comment by orkhanahmadov** [comment]
Requirement from backend is to submit all checkin times in [epoch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_epoch_timestamps_and_invalid_date).

When documenting that endpoint, I forgot that JS epoch is in milliseconds, unlike in PHP for example, in seconds. That's why you use that value and submit. the date shows up as some time in 2008. It needs to be divided by 1000 to get he the value in seconds, instead of milliseconds.

Good catch!

**Comment by orkhanahmadov** [comment]
@joanna-pw Requirement from backend is to submit all checkin times in [epoch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_epoch_timestamps_and_invalid_date).

When documenting that endpoint, I forgot that JS epoch is in milliseconds, unlike in PHP for example, in seconds. That's why you use that value and submit. the date shows up as some time in 2008. It needs to be divided by 1000 to get he the value in seconds, instead of milliseconds.

Good catch!

**Pull request merged**
